name: mobile-asr-models

on:
  push:
    branches:
      - asr-mobile

  workflow_dispatch:


concurrency:
  group: mobile-asr-models-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile-asr-models:
    if: github.repository_owner == 'k2-fsa' || github.repository_owner == 'csukuangfj' || github.repository_owner == 'csu-fangjun'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python3 -m pip install onnxruntime onnx

      - name: Run
        shell: bash
        run: |
          cd scripts/mobile-asr-models
          ./run.sh
